spring:
  application:
    name: notification-service
  jpa:
    show-sql: true

server:
  port: 7003

management:
  endpoints:
    enabled-by-default: true

springdoc:
  swagger-ui:
    path: /swagger-ui