CREATE TABLE IF NOT EXISTS BASVURU_BILGILERI (
  BASVURU_NUMARASI BIGINT NOT NULL,
  TCKN varchar(11) NOT NULL,
  ISIM varchar(50) NOT NULL,
  SOYISIM varchar(50) NOT NULL,
  GELIR DOUBLE PRECISION NOT NULL,
  TELEFON varchar(11) NOT NULL,
  DOGUM_TARIHI DATE NOT NULL,
  TEMINAT DOUBLE PRECISION,
  KKB_SKORU INT,
  SONUC varchar(4),
  KREDI_LIMIT DOUBLE PRECISION,
  PRIMARY KEY (BASVURU_NUMARASI)
);

CREATE SEQUENCE hibernate_sequence START 1;

INSERT INTO BASVURU_BILGILERI (BASVURU_NUMARASI,     TCKN       ,  ISIM   , SOYISIM  , GELIR,    TELEFON  , DOGUM_TARIHI, TEMINAT, KKB_SKORU , SONUC , KREDI_LIMIT)
VALUES              (      0         , '12345678910'  , 'vahap' , 'ozaltay', 10000, '5359991914', '1914-01-16',   1000 , 1501      , 'onay',    15000);